#Converting to uppercase and lowercase....

fruit1 = "APPLE"
fruit2 = "orange"

print(fruit1.lower())               #converts to lower case...
print(fruit2.upper())               #converts to upper case....